### ISSUE TITLE
Error: forEach on unknown length arrays

### ISSUE THREAD

**Issue by julorenz** [p2o-lab/pimad-core#5]
some arrays may contain just one element, those are therefore treated as objects

forEach breaks at that point

Ideas: 
1) Array.isArray() with if else

2) const internalElementArray = amlService.InternalElement.constructor === Object? [amlService.InternalElement as object as DataItemInstanceList] : amlService.InternalElement;

3) Array.of() didnt work so far for me
4) [...object] didnt work for me

**Comment by cheidelbach** [comment]
var array = ["Hello"]

array.forEach(element => {
    console.log(element)
})

This prints: "Hello" to the command line. Working fine. Do you have an example of the the issue? Maybe the code i executed is to simple.

**Comment by julorenz** [comment]
>         /* Easier handling of 'single' and 'multiple' sources in one code section. Therefore a single source is
>         transferred to an array with one entry. */
>         if(!(Array.isArray(sourceList.InternalElement))) {
>             sourceList.InternalElement = [sourceList.InternalElement];
>         }
>         // Handle the SourceList. Mainly extracting the server communication interfaces.
>         sourceList.InternalElement.forEach((sourceListItem: DataItemSourceList) => {

MTPs failed in case there was just a single "Object" included
e.g. just one InternalElement
While debugging the error on "sourceList.InternalElement.forEach" 

> ERROR TypeError: res.forEach is not a function

https://stackoverflow.com/questions/57160451/error-typeerror-res-foreach-is-not-a-function/57160520

was identified to be caused on InternalElement being an object and on that prototype foreach isnt defined

I handled that for now as described above. I#ll close that Issue for now, in case there is a better solution, you may want to reopen it.
